# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - export IMAGE_TAG=$(echo -en $CI_BUILD_REF_NAME | tr -c '[:alnum:]_.-' '-')
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build 
        --build-arg=http_proxy=${HTTP_PROXY}
        --build-arg=https_proxy=${HTTPS_PROXY}
        --build-arg=HTTP_PROXY=${HTTP_PROXY}
        --build-arg=HTTPS_PROXY=${HTTPS_PROXY}
        --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
