db_common: &db_common
  methods:
    - probe_db
  opts:
    connection_string: dbname={{DB_NAME}} user={{DB_USER}} host={{DB_HOST}} password={{DB_PASS}} port={{DB_PORT}}

# Web server config
server:
  listen_address: 0.0.0.0
  listen_port: {{GITLAB_MONITOR_PORT}}

# Probes config
probes:
  # Each key corresponds to an endpoint, so here metrics are available at http://localhost:9168/git.
  # The server will search for a prober using the format `KeyProber`, so here it will be `GitProber`.
  # If there's no prober matching the format above, `class_name` key should be provided (see `git_process` below).
#XXX Git related metrics do not work well, see: https://gotfix.com/docker/gitlab/issues/57
# git:
#   # Methods to call on the prober
#   methods:
#     - probe_pull
#     - probe_push
#   # Options to pass to the prober class initializer
#   opts:
#     source: {{GITLAB_REPOS_DIR}}

# git_process:
#   class_name: GitProcessProber # `class_name` is redundant here
#   methods:
#   - probe_git
#   opts:
#     quantiles: true

  # We can group multiple probes under a single endpoint by setting the `multiple` key to `true`, followed
  # by probe definitions as usual.
  database:
    multiple: true
    blocked_queries:
      class_name: Database::BlockedQueriesProber
      <<: *db_common
#XXX Does not work on Gitlab CE due to project.mirror column missing. Ref: https://gotfix.com/docker/gitlab/issues/55
    ci_builds:
      class_name: Database::CiBuildsProber
      <<: *db_common
    tuple_stats:
      class_name: Database::TuplesProber
      <<: *db_common
    rows_count:
      class_name: Database::RowCountProber
      <<: *db_common
    slow_queries:
      class_name: Database::SlowQueriesProber
      <<: *db_common
    stuck_idle_in_transactions:
      class_name: Database::StuckIdleInTransactionsProber
      <<: *db_common
    vacuum_queries:
      class_name: Database::VacuumQueriesProber
      <<: *db_common

  process:
    methods:
      - probe_memory
      - probe_age
      - probe_count
    opts:
      - pid_or_pattern: "sidekiq .* \\[.*?\\]"
        name: sidekiq
      - pid_or_pattern: "unicorn worker\\[.*?\\]"
        name: unicorn
      - pid_or_pattern: "git-upload-pack --stateless-rpc"
        name: git_upload_pack
        quantiles: true

  sidekiq:
    methods:
      - probe_queues
      - probe_jobs
      - probe_workers
      - probe_retries
      - probe_dead
    opts:
      redis_url: "redis://{{REDIS_PASSWORD_GL}}{{REDIS_HOST}}:{{REDIS_PORT}}"
